require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/active_ingredients", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ActiveIngredient. As you add validations to ActiveIngredient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ActiveIngredient.create! valid_attributes
      get active_ingredients_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      active_ingredient = ActiveIngredient.create! valid_attributes
      get active_ingredient_url(active_ingredient)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_active_ingredient_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      active_ingredient = ActiveIngredient.create! valid_attributes
      get edit_active_ingredient_url(active_ingredient)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ActiveIngredient" do
        expect {
          post active_ingredients_url, params: { active_ingredient: valid_attributes }
        }.to change(ActiveIngredient, :count).by(1)
      end

      it "redirects to the created active_ingredient" do
        post active_ingredients_url, params: { active_ingredient: valid_attributes }
        expect(response).to redirect_to(active_ingredient_url(ActiveIngredient.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ActiveIngredient" do
        expect {
          post active_ingredients_url, params: { active_ingredient: invalid_attributes }
        }.to change(ActiveIngredient, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post active_ingredients_url, params: { active_ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested active_ingredient" do
        active_ingredient = ActiveIngredient.create! valid_attributes
        patch active_ingredient_url(active_ingredient), params: { active_ingredient: new_attributes }
        active_ingredient.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the active_ingredient" do
        active_ingredient = ActiveIngredient.create! valid_attributes
        patch active_ingredient_url(active_ingredient), params: { active_ingredient: new_attributes }
        active_ingredient.reload
        expect(response).to redirect_to(active_ingredient_url(active_ingredient))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        active_ingredient = ActiveIngredient.create! valid_attributes
        patch active_ingredient_url(active_ingredient), params: { active_ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested active_ingredient" do
      active_ingredient = ActiveIngredient.create! valid_attributes
      expect {
        delete active_ingredient_url(active_ingredient)
      }.to change(ActiveIngredient, :count).by(-1)
    end

    it "redirects to the active_ingredients list" do
      active_ingredient = ActiveIngredient.create! valid_attributes
      delete active_ingredient_url(active_ingredient)
      expect(response).to redirect_to(active_ingredients_url)
    end
  end
end
