require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/medication_active_ingredients", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MedicationActiveIngredient. As you add validations to MedicationActiveIngredient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MedicationActiveIngredient.create! valid_attributes
      get medication_active_ingredients_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
      get medication_active_ingredient_url(medication_active_ingredient)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_medication_active_ingredient_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
      get edit_medication_active_ingredient_url(medication_active_ingredient)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MedicationActiveIngredient" do
        expect {
          post medication_active_ingredients_url, params: { medication_active_ingredient: valid_attributes }
        }.to change(MedicationActiveIngredient, :count).by(1)
      end

      it "redirects to the created medication_active_ingredient" do
        post medication_active_ingredients_url, params: { medication_active_ingredient: valid_attributes }
        expect(response).to redirect_to(medication_active_ingredient_url(MedicationActiveIngredient.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MedicationActiveIngredient" do
        expect {
          post medication_active_ingredients_url, params: { medication_active_ingredient: invalid_attributes }
        }.to change(MedicationActiveIngredient, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post medication_active_ingredients_url, params: { medication_active_ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested medication_active_ingredient" do
        medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
        patch medication_active_ingredient_url(medication_active_ingredient), params: { medication_active_ingredient: new_attributes }
        medication_active_ingredient.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the medication_active_ingredient" do
        medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
        patch medication_active_ingredient_url(medication_active_ingredient), params: { medication_active_ingredient: new_attributes }
        medication_active_ingredient.reload
        expect(response).to redirect_to(medication_active_ingredient_url(medication_active_ingredient))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
        patch medication_active_ingredient_url(medication_active_ingredient), params: { medication_active_ingredient: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested medication_active_ingredient" do
      medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
      expect {
        delete medication_active_ingredient_url(medication_active_ingredient)
      }.to change(MedicationActiveIngredient, :count).by(-1)
    end

    it "redirects to the medication_active_ingredients list" do
      medication_active_ingredient = MedicationActiveIngredient.create! valid_attributes
      delete medication_active_ingredient_url(medication_active_ingredient)
      expect(response).to redirect_to(medication_active_ingredients_url)
    end
  end
end
